package model.afclassification;

/**
 * The enumeration of possible client context information properties
 */
public enum Property {
    CONNECTION_CONNECTED,
    CONNECTION_TYPE,
    CONNECTION_WIFI_IP_ADDRESS,
    CONNECTION_WIFI_BSSID,
    CONNECTION_WIFI_SSID,
    BATTERY_CAPACITY,
    BATTERY_CHARGING,
    BATTERY_CHARGING_TYPE,
    BATTERY_TEMPERATURE,
    DEVICE_RESOLUTION_WIDTH,
    DEVICE_RESOLUTION_HEIGHT,
    DEVICE_RESOLUTION_INCHES,
    DEVICE_NAME,
    DEVICE_PRODUCT,
    DEVICE_MODEL,
    DEVICE_API_LEVEL,
    LOCATION_LATITUDE,
    LOCATION_LONGITUDE,
    LOCATION_ALTITUDE,
    LOCATION_SPEED,
    APPLICATION_STATE_USER,
    APPLICATION_STATE_LAST_SCREEN;
}
